# radioglobe package init
# Expose package version from _version.py written by setuptools_scm at build time.
try:
    # _version.py is generated by setuptools_scm (write_to)
    from ._version import version as __version__  # type: ignore
except Exception:
    __version__ = "0+unknown"

__all__ = ["__version__"]
